# @name Get-Product
GET http://localhost:3333/product?page=1

###
# @name Get-Product-id
GET http://localhost:3333/product/fae1d1f2-c856-4729-8d37-f3d72cb62a76


###
# @name Create-Product
POST http://127.0.0.1:3333/product
Content-Type: application/json

{
  "name": "Monitor",
  "description": "Monitor LG 21.pol 144fps",
  "color": "Preto",
  "price": 2500
}

###
# @name Update-Product
PUT http://localhost:3333/product/fae1d1f2-c856-4729-8d37-f3d72cb62a76
Content-Type: application/json

{
  "name": "Monitor LG",
  "description": "Monitor LG 21.pol 144fps",
  "color": "Preto",
  "price": 2500

}

###
# @name Delete-Product
DELETE http://localhost:3333/product/0e30090b-d634-4307-b387-ade72a68f00e
Content-Type: application/json

